name: Merge branch to master on success

on:
  push:
    branches:
      - '*'

jobs:
  merge_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run test.py
      run: python test.py
      id: test_result
    - name: Merge branch with master
      if: steps.test_result.outcome == 'success' && github.ref != 'refs/heads/master'
      uses: actions/github-script@v4
      with:
        script: |
          const { data } = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Merge branch into master',
            head: context.ref,
            base: 'master'
          })
          const merge = await github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: data.number,
            commit_title: 'Merge branch into master',
            merge_method: 'squash'
          })
