name: Merge branch to master on test success

on:
  push:
    branches:
      - itaimoor

jobs:
  merge_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Run test.py
      run: python test.py
      id: test_result
    - name: Copy example.txt to master
      if: steps.test_result.outcome == 'success'
      run: |
        cp itaimoor/example.txt .
        git add example.txt
        git commit -m "Add example.txt from itaimoor branch"
        git push origin master
