name: Merge branch to master on test success

on:
  push:
    branches:
      - itaimoor

jobs:
  merge_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Run test.py
      run: python test.py
      id: test_result
    - name: Merge branch with master
      if: steps.test_result.outcome == 'success'
      run: |
        git checkout master
        git merge --no-ff ${{ github.head_ref }} -m "Merge branch '${{ github.head_ref }}' into master"
        git push origin master
